package com.company;

public enum Fields {
    COMPUTER_ENGINEERING,
    ELECTRIC_ENGINEERING,
    MECHANICAL_ENGINEERING,
    CIVIL_ENGINEERING,
    ARCHITECTURAL_ENGINEERING,
    CHEMICAL_ENGINEERING,
    PETROLEUM_ENGINEERING
}